language: php
php:
  - 5.4
#  - 5.5
#  - 5.6

before_script:
  - composer selfupdate
  - composer install --no-progress
  - ./bin/doctrine orm:schema:drop --force
  - ./bin/doctrine orm:schema:create

script:
  - ./bin/phpunit
