# config/v1.yml

# Triggers a build that will get sent to the results site and the dispatcher.
run:
  path: /job
  defaults: { _controller: 'API\V1Controller::jobRun' }
  methods: [POST]

# Pulls the results of the job from the results site and the dispatcher.
status:
  path: /job/{id}
  defaults: { _controller: 'API\V1Controller::jobStatus' }
  methods: [GET]

# Authenticate with the API to gain access to starting, stopping and restarting jobs.
auth:
  path: /auth
  defaults: { _controller: 'API\V1Controller::auth' }

# Get the overall health of the system.
status:
  path: /status
  defaults: { _controller: 'API\V1Controller::status' }
