jenkins:
  host:  localhost
  port:  8080
  protocol: http
  token: 123456
  job:   test

db.options:
  driver: pdo_sqlite

# How long before we have to update our build status from Jenkins? In seconds.
job.record.expire: 15
